import { Router } from "express";

import { authRouter } from "./auth.routes.js";
// import bankRouter from './bank.routes.js';
// import customerRouter from './customer.routes.js';
// import dashboardRouter from './dashboard.routes.js';
import { emailTemplateRouter } from "./email-template.routes.js";
// import loanRouter from './loan.routes.js';
// import clientRouter from './client.routes.js';
// import permissionRouter from './permissions.routes.js';
// import reviewRouter from './review.routes.js';
import { roleRouter } from "./role.routes.js";
// import segmentRouter from './segment.routes.js';
// import stateRouter from './state.routes.js';
import { tenantRouter } from "./tenant.routes.js";
// import testRoutes from './test.routes.js';
import { sessionRouter } from "./session.routes.js";
import { userRouter } from "./user.routes.js";
// import webhookRouter from './webhook.routes.js';

export const appRouter = Router();

appRouter.use("/auth", authRouter);
// appRouter.use('/banks', bankRouter);
// appRouter.use('/clients', clientRouter);
// appRouter.use('/customers', customerRouter);
// appRouter.use('/dashboard', dashboardRouter);
appRouter.use("/email-templates", emailTemplateRouter);
// appRouter.use('/loans', loanRouter);
// appRouter.use('/permissions', permissionRouter);
// appRouter.use('/reviews', reviewRouter);
appRouter.use("/roles", roleRouter);
// appRouter.use('/segments', segmentRouter);
appRouter.use("/sessions", sessionRouter);
// appRouter.use('/states', stateRouter);
appRouter.use("/tenants", tenantRouter);
// appRouter.use('/test', testRoutes);
// appRouter.use('/transactions', transactionRouter);
appRouter.use("/users", userRouter);
// appRouter.use('/wallets', walletRoutes);
// appRouter.use('/webhooks', webhookRouter);
